version: '3'

volumes:
  prometheus_data:
  grafana-data: 


services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: Dedyakhin_IV-netology-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - Dedyakhin_IV-my-netology-hw
    restart: always

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro,rslave
      - /:/host:ro,rslave   # Ensure using 'rslave' for /host mount
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - Dedyakhin_IV-my-netology-hw
    restart: always
    deploy:
      mode: global


  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: Dedyakhin_IV-netology-pushgateway
    ports:
      - 9091:9091
    networks:
     - Dedyakhin_IV-my-netology-hw
    depends_on: 
      - prometheus
    restart: unless-stopped
    

  grafana:
    image: grafana/grafana
    container_name: Dedyakhin_IV-netology-grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
    ports:
      - 80:3000
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - Dedyakhin_IV-my-netology-hw
    depends_on: 
      - prometheus
    restart: unless-stopped



       
  



networks:
  Dedyakhin_IV-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16    
          gateway: 10.5.0.1
